project:
  type: website

website:
  title: "Curso GEI-429: Teledetecci贸n "
  page-navigation: true
  logo: ./fig/ECG-UNA.png
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - text: "Temas"
        menu:
          - ./docs/c01_intro/c01_intro.qmd
          - ./docs/c02_basefisica/c02_basefisica.qmd
      - about.qmd
  right:
      - icon: twitter
        href: https://twitter.com/Sethraz
        aria-label: Sethraz Twitter
      - icon: github
        href: https://github.com/sethraz/GEI-429-Teledeteccion
        aria-label: Curso Teledetecci贸n GitHub


  sidebar: 
    style: "docked"
    search: true
    contents: 
      - section: "Introducci贸n a la Teledetecci贸n"
        contents:
          - ./docs/c01_intro/c01_intro.qmd
          - ./docs/c02_basefisica/c02_basefisica.qmd
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

