project:
  type: website
  output-dir: docs

website:
  title: "GEI-429: Teledetección"
  image: /fig/ecg_una.png
  page-navigation: true
  logo: /fig/ecg_white.png
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - text: "Temas"
        menu:
          - ./temas/c01_intro/c01_intro.qmd
          - ./temas/c02_basefisica/c02_basefisica.qmd
      - about.qmd
  right:
      - icon: twitter
        href: https://twitter.com/Sethraz
        aria-label: Sethraz Twitter
      - icon: github
        href: https://github.com/sethraz/GEI-429-Teledeteccion
        aria-label: Curso Teledetección GitHub

  sidebar:
    - id: inicio
      title: "Contenidos"
      style: "docked"
      search: true
      contents: 
        - section: "Aspectos generales"
          contents: 
            - ./temas/c01_intro/c01_intro.qmd
            - ./temas/c02_basefisica/c02_basefisica.qmd
            - ./temas/c03_sensores/c03_sensores.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
editor: visual

